FROM alpine:3.22
RUN apk add --no-cache curl && \
  curl -L https://github.com/golang-migrate/migrate/releases/download/v4.18.1/migrate.linux-amd64.tar.gz | tar xz && \
  mv migrate /usr/local/bin/migrate
COPY migrations /migrations
CMD ["migrate", "-path", "/migrations", "-database", "$DATABASE_URL", "up"]