---
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-service" (include "app.name" .) }} #task-mgr-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 80
      targetPort: {{.Values.app.port}} # Videresender webtrafikk fra port 80 til appens port 8080
  selector:
    app: {{ include "app.fullname" . }}
  type: ClusterIP # Bruk ClusterIP internt, eller ClusterIP + Ingress for ekstern trafikk