---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: task-mgr-secret
  namespace: task-mgr
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgApYoPV1JKjD51kAHGd+2XbfGj3lOgKvs46h2UvW2aDB59hNQxTOBkTKTJ829ZGJK/1dJgrTvei8+SHReqiaoZ+97yHrKpM2hQw7uMDVCNZqZGdsbkbVJI2b4ImxQw41YRqgRt909AXlJ7dWYsDPO6z2VtVx2igpjZ6in624sTKEtYnKc//jCNvlE9B63V4qzGMN7R8UG0faK9h5jyfJtyubqQ8e5TbygyebF6/2+7vpz5ox7IYr9MSDLTc6/lLCw5iHZdiOhuyDW+9gzeuIGR8TTk5qvPdbs7tpmtPTP6zr+ypDT72LjKMzZ4ainMmM1JWbie/lEu5rcNUAtRlCKodMC/fiBsjMCkcaXAWJ76KbMkdeyaM6mwgvvoNQfnYIBTV4NFzMLGBSEAmIwCYrdicnTtAur+YK2h5coGv/eXabbxW7DOL5TuHTWDC1mM5IkLSLTBB/W10BYfcGZTCHSGK7QgZpg2w3bVQ0o6pam7W9B24KX2slBbEodXxhSPwv5whZlw6zKrqi0iAx4SNwJkqVYHsGDIEceRr0iw9E6arXQBSwVrpSPxjARpzEo3tsOE3O4h9VpPVs74ercn82+BJX4//j3BUi2/OMwPtpIsY5HyhM4SBSdpq8WMMpRX/xmloZLDwgBRxNHt0S+3iLNNAmTHo0s7O8yQOrR40LWy03AZbTf1bnr8k1T+u6aohPLfODUyJnqEvBg==
    POSTGRES_USER: AgBLlxBbFTVEQimoax7bv9dASIi5rYyHx7FOQJUFjG5Ms2JTi8xvT+G5aj6nqGbPQFnijg842YKfv+93xrGZcCTAYalD8G50jp0LVRQwytn2OYum8iXQ5HvZoWeFa9bIfzG78JeP6D59dkPYReqcrhKuNzEoPDz8dWFV96WXtvP7C8txZipcyKpRoLfNU5aWPUTY/oPmBswsdxM+NpWSAYGQZ1PQDxYDI9X2zWErv8uSBxQRSn9lbGM13RGF4LpArDd1h1I7ml9mYZh0DJj32KH6XxtvedviP7yPis8Agew1dJhCXhH9hLFfDbKMudHs4eB5gRzObqV9wQXyHKMeobg2a5f6nZTADdksT03zbW4Z993OTr/WgTymEBFpstr5w2lzRN81QQdz9UnRoNHrQc4iMKUbS0u8nrkTH0jki2JrmuxM2EDZAzampfx3aTwzFKQMkYymAC9nudBu5uvGeNaab0OdsZOZFTUbld11KvmxsX0AZlGD2fFlJ5hQenMHVT0jJT5cnNA29Y7g0CjW9ZdaZrcdf/Tw3FilMMeX+HzNdMELJL/q41SJBUHbIpBNZsMw+7sfHrc0lXwN6HRsDhaSUr68H45MEVmtnabgki6DXdQ1GU+dCJW+6HM0mCkk48FSEr6Z5r2fhcGQ8k9w+X2o7qa0m80KjTYcQ02KLn9ecgHR4IBFba/8VA6/o2HrrJqr84RL1uLosg==
  template:
    metadata:
      name: task-mgr-secret
      namespace: task-mgr
    type: Opaque
