registry: homelab:30500

app:
  port: 8072
  replicas: 2
  env:
    jwksurl: "https://gitlab.skead.no/-/jwks"
    jwtaud: "https://onboarding-flyt.skead.no"
    alwdns: "lagring" # Kan være flere da kommaseparert

postgres:
  database: taskdb
  port: 5432
  storage: 1Gi

ingress:
  host: homelab
  path: /task-mgr-api

image:
  app: task-mgr
  migrate: task-mgr-migrate
