registry: homelab:30500

app:
  port: 8072
  replicas: 2

postgres:
  database: taskdb
  port: 5432
  storage: 1Gi

ingress:
  host: homelab
  path: /task-mgr-api

image:
  app: task-mgr
  migrate: task-mgr-migrate
